### PR TITLE
Write your first bot using Nuntius.

### PR DESCRIPTION
**Pull request by RoySegall**
gizra_s_blog_

### CODE REVIEW

**Comment by RoySegall** [comment]
@IshaDakota Can you have a look on this? 10x.

**Comment by RoySegall** [comment]
Don't merge yet - I'll tell when. I'm updating some stuff and the screen shots need to be replaced.

**Comment by RoySegall** [comment]
OK - this one ready for review:

**Comment by IshaDakota** [comment]
@RoySegall can you take a look at this and see if you approve my changes?

**Comment by RoySegall** [comment]
Yeah, looks good. 10x.

**Pull request merged**
