### PR TITLE
Name and title changes

### PR DESCRIPTION
**Pull request by DavidBronfen**
#504

### CODE REVIEW

**Comment by DavidBronfen** [comment]
@DavidKohav 
Please add screenshots of your's and Rachel's hover (to see the changes).
(I can't run the project on my machine)

**Comment by DavidKohav** [comment]
selection_005

**Comment by DavidKohav** [comment]
selection_006

**Comment by DavidKohav** [comment]
Looking good

**Comment by DavidBronfen** [comment]
@DavidKohav 
Great, Thank you.

**Pull request merged**
