### PR TITLE
Blog post: OG8 development mindset

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@IshaDakota I still need to add two images, but I'd be happy to get your review. I'd be happy to publish tomorrow or on Thursday.

**Comment by amitaibu** [comment]
Taking advantage of time zone differences :) - @RachelBaram if you happen to be around and got time for some proof reading.

**Comment by amitaibu** [comment]
@liatsade checkout  the image `app/assets/images/posts/og8-development-mindset/image2.jpg`. It involves a pen, a small glass, and a business card acting as a ruler 😉

**Comment by liatsade** [comment]
@amitaibu I think I can get all this equipment, but you forgot to mention your drawing skills, which is better than mine ;-)

**Comment by amitaibu** [comment]
@liatsade fear is the mind killer 😄

**Comment by liatsade** [comment]
@amitaibu you absolutely right!

**Comment by amitaibu** [comment]
Back to you Adam, if you can

**Comment by amitaibu** [comment]
Deployed: http://www.gizra.com/content/og8-development-mindset/

**Pull request merged**
