### PR TITLE
Tachyons is fun

### PR DESCRIPTION
**Pull request by amitaibu**
screenshot-2018-5-24 rebuild or refresh your website how about neither

(completely ripped off from https://tachyons.io/components/articles/title-highlight-header-cover/index.html)

I've played around with tachyons, and I already really like it. Takes a little learning for the abbreviations, but I think I already grok most of the concepts.

### CODE REVIEW

**Comment by amitaibu** [comment]
screenshot-2018-5-26 blog

**Comment by amitaibu** [comment]
screenshot-2018-5-26 web strategy design development gizra

**Comment by amitaibu** [comment]
@IshaDakota @RachelBaram my "playing around" is starting to get some results, and I wonder what you are thinking of them.

**Comment by RachelBaram** [comment]
From a design perspective, since our site is so text heavy, the color blocking, if done right, can be really nice.  The elements that I think make  https://tachyons.io/components/articles/title-highlight-header-cover/index.html) work are:
1. the right balance between white space and color (I like the idea but there needs to be more white space than color)
2. font choices and text width (I believe should be the first improvements I wanted to make to the home page)

**Comment by IshaDakota** [comment]
@amitaibu 
After a few hours on the weekend exploring...

PROS
1. Indeed, Tachyons is fun - cool concept and pretty easy to get used to.
2. I like the idea of functional CSS - normally doing component-driven design requires a lot of discipline and planning. The tools available to enforce discipline (like Pattern Lab) are pretty laborious.
3. I'll believe what they say about performance. 

CONS
1.  In a world of flexbox and CSS-Grid, I'm less convinced that we need CSS frameworks anymore. For sure not for the grid. Maybe for the design components, but that doesn't really help us in any custom design situation.
2. related to the above, I increasingly feel that content and layout should live separately. CSS-Grid, in particular allows this in ways that we couldn't do before.
3. The Tachyons method injects so much layout and design into the HTML that it really gets hard to read and doesn't seem that semantic.

As an experiment, I created the Tachyons homepage that you created, but instead stripped all of the frameworks and used flexbox and grid for layout in #708

**Comment by amitaibu** [comment]
Good points. I agree with most of them.

> In a world of flexbox and CSS-Grid

I totally agree about not needing tachyons for layout. grid is quite powerful, and we can use as is.

>  I increasingly feel that content and layout should live separately.

I guess this is where we differ. I now days feel that semantic is a bit of a lie, or at least too purist for my taste. That is, as you [demonstrated](https://www.gizra.com/content/prototype-with-css-grid/) is a very powerful concept along with new css tools, however:

When you have more than a single page -- and you have different components/ objects scattered in different pages you end up with css files getting bigger and bigger. My experience shows me that HTML is more maintainable than css files. The end of all CSS files are too become bloated, and for devs to be scarred to remove existing declarations.

Further more, while semantic is a good concept, in reality you 99% have a single view for it.

Lastly, and probably minor - when reviewing  I find it easier to kind of get an image in my head of the HTML, as the styling is part of it.

**Comment by amitaibu** [comment]
Closed in favor of #708

**Pull request closed without merging**
