### PR TITLE
Blog post: WebdriverIO with multiremote technique

### PR DESCRIPTION
**Pull request by mariano-dagostino**

### CODE REVIEW

**Comment by nedSaf** [comment]
@mariano-dagostino That's really nice :)

**Comment by amitaibu** [comment]
👍  

Not a must, but a piece I would be interested in reading/ seeing is integration with Travis. Does it "simply work?"

**Comment by adamhstewart** [comment]
Fixing blockquote style as part of this PR.

webdriverio_tests_with_multiple_browsers

**Comment by adamhstewart** [comment]
deployed!

**Pull request merged**
