### PR TITLE
Site without framework

### PR DESCRIPTION
**Pull request by adamhstewart**

### CODE REVIEW

**Comment by IshaDakota** [comment]
Homepage:

fireshot capture 526 - web strategy design development i gizra - http___localhost_3000_

**Comment by IshaDakota** [comment]
merged blog page

fireshot capture 529 - stripped down to the essence_ _ - http___localhost_3000_content_adding-value_

and blog landing
image

**Comment by IshaDakota** [comment]
fireshot capture 531 - project portfolio - http___localhost_3000_projects_

**Comment by adamhstewart** [comment]
image


image

**Comment by adamhstewart** [comment]
all done.

**Comment by adamhstewart** [comment]
Only 48 files - what could go wrong?

**Pull request merged**
