### PR TITLE
Efrat to be Director of Gizra Israel/ Europe post

### PR DESCRIPTION
**Pull request by amitaibu**
Based of https://github.com/Gizra/gizra.com/pull/613

### CODE REVIEW

**Comment by amitaibu** [comment]
@efratn fyi 😄

**Comment by amitaibu** [comment]
gizra_s_blog

**Comment by amitaibu** [comment]
(Should be merged before https://github.com/Gizra/gizra.com/pull/613)

**Comment by IshaDakota** [comment]
@amitaibu should have read before merging #613

**Comment by IshaDakota** [comment]
merged & deployed.

**Pull request merged**
