### PR TITLE
Blog Post: 12 Things I learned at my first DrupalCon

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@IshaDakota care to do a review? (I've assigned to you, as you have the site setup locally, and it would be easier for you to see how the post will look with `grunt serve`)

(Please check also the caption of the images)

I'd be happy to publish today

**Comment by IshaDakota** [comment]
Looking at I first thing today so it can be published.

**Comment by amitaibu** [comment]
👍 

(cc @kazabooboo @RachelBaram)

**Comment by IshaDakota** [comment]
@amitaibu ready to publish from my POV.

**Comment by kazabooboo** [comment]
upscale the server!

**Comment by IshaDakota** [comment]
@kazabooboo add more cattle.

**Comment by amitaibu** [comment]
Merged and deployed - http://www.gizra.com/content/12-things-learned-first-drupalcon/

Thanks!

**Pull request merged**
