### PR TITLE
Balance headers by right justifying menu

### PR DESCRIPTION
**Pull request by IshaDakota**
#415 

As opposed to aligning header to new margins, give header some balance to lessen the visual disruption

**Homepage**
fireshot capture 22 - design web development i gizra - http___0 0 0 0_9000_

**Blog landing**
fireshot capture 23 - gizra s blog - http___0 0 0 0_9000_blog_

**Blog post**
fireshot capture 24 - a job posting goes viral - http___0 0 0 0_9000_content_job-post-goes-viral_

### CODE REVIEW

**Comment by IshaDakota** [comment]
**Mobile**
fireshot capture 25 - a job posting goes viral - http___0 0 0 0_9000_content_job-post-goes-viral_

fireshot capture 26 - a job posting goes viral - http___0 0 0 0_9000_content_job-post-goes-viral_

**Comment by IshaDakota** [comment]
A few notes:

- I uppercased the menu to give it more weight.
- Pulled the "blog" title out of the header because it looked weird.
- Did not fix any vertical rhythm or typography here - that will also help the issue in #415 by providing better separation between the header and the main body elements.

**Comment by RachelBaram** [comment]
I like this solution. The block lettering is a great change. Something little... can you bring the text box on the homepage (slogan,etc) down just a little. The top of "Take a leap of faith..." lines up with the top of the mountain peak (not the guy, the mountain.)

**Comment by IshaDakota** [comment]
Yes. Definitely on the spacing. I saved that for the typography issue, but
that will help a lot on all pages.

**Comment by amitaibu** [comment]
Looks good. Can you please also take care of `/contact` and `/jobs/experienced-web-dev/`

**Comment by amitaibu** [comment]
(in terms of logo's position)

**Comment by IshaDakota** [comment]
> Looks good. Can you please also take care of /contact and /jobs/experienced-web-dev/

Done. Also some other layout tweaks that will allow this to be deployed without upsetting some pages.

**Comment by IshaDakota** [comment]
**Homepage**
fireshot capture 29 - design web development i gizra - http___0 0 0 0_9000_

**Contact**
fireshot capture 30 - contact gizra - http___0 0 0 0_9000_contact_

**Jobs**
fireshot capture 31 - looking for experienced web d_ - http___0 0 0 0_9000_jobs_experienced-web-dev_

**Comment by amitaibu** [comment]
Actually, I'll merge this. @IshaDakota, if you can you take of previous comment in a follow up.

**Pull request merged**
