### PR TITLE
Proposed Header/Sidebar

### PR DESCRIPTION
**Pull request by adamhstewart**
Toward a sleeker header:

gizra_s_blog

Larger sidebar:
gizra_s_blog_and_gizra_ _-bash_ _125x22

### CODE REVIEW

**Comment by IshaDakota** [comment]
^^ can't really tell by screenshot, but sidebar menu is "massive" -- would like it bigger actually.

**Comment by amitaibu** [comment]
Thanks, early comments:

1. By moving the menu to the right - when you click on it, the sidebar actually opens in the left.
1. Also, I think we should keep the/a tag line - one that immediately tells ppl what kind of stuff we do, without them needing to dig in too dip to find out.

**Comment by IshaDakota** [comment]
> By moving the menu to the right - when you click on it, the sidebar actually opens in the left.

I think that's fine, intuitive UI.

> Also, I think we should keep the/a tag line

see #561 - I propose to move just as a tagline to the homepage. Let logos be logos and tag lines be tag lines. Unless you're Nike, then you can "just do it."

**Comment by IshaDakota** [comment]
>  think that's fine, intuitive UI.

Although SUI makes it easy to move it right:

image

(that white border is some figment of the screen capture's imagination - it's not there)

**Pull request closed without merging**
