### PR TITLE
Disqus - HTTPS

### LINKED ISSUE #593: Add SSL to gizra.com [1h]
And force https. Because why not :)

### PR DESCRIPTION
**Pull request by AronNovak**
will fix #593

### CODE REVIEW

**Comment by IshaDakota** [comment]
shoot... I made a mental note to check that.... and then didn't

**Comment by AronNovak** [comment]
@IshaDakota sorry for this, after my check before changing CloudFlare to force HTTPS, i spotted this.

**Comment by IshaDakota** [comment]
merged & deployed... again!

**Comment by AronNovak** [comment]
@IshaDakota thanks for the prompt action, just reconfigured CloudFlare

**Pull request merged**
