### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by IshaDakota**
#438

### CODE REVIEW

**Comment by IshaDakota** [comment]
fireshot capture 53 - design web development i gizra - http___0 0 0 0_9000_

**Comment by IshaDakota** [comment]
@amitaibu @RachelBaram this is ready for review by both of you.

**Comment by amitaibu** [comment]
Looks good. @RachelBaram if you are ok, I can deploy

**Comment by RachelBaram** [comment]
Do it. :)

**Comment by amitaibu** [comment]
Thanks, deployed!

**Pull request merged**
