### PR TITLE
Added alvaro photo.

### PR DESCRIPTION
**Pull request by DavidBronfen**
#555

### CODE REVIEW

**Comment by amitaibu** [comment]
The background indeed looks bad (just tried with chrome dev to see how it would look). Also, it's in the wrong proportion

the_team

@alvar0hurtad0 can you please provide a different image?

**Comment by alvar0hurtad0** [comment]
@amitaibu should I take a new picture or just crop and scale?

I've cropped a plain background to extend as needed.

**Comment by amitaibu** [comment]
@DavidBronfen ^^ please guide Alvaro in the process

**Comment by DavidBronfen** [comment]
@alvar0hurtad0 
Detailed instructions sent in private message (hangouts)
@amitaibu 
Tomorrow I'll try to fix the one above just for now.

**Comment by amitaibu** [comment]
> Detailed instructions sent in private message (hangouts)

Worth adding them to the README

**Comment by DavidBronfen** [comment]
@amitaibu OK! :smile:

**Comment by alvar0hurtad0** [comment]
@DavidBronfen if this one is OK I can add into a PR myself:

**Comment by alvar0hurtad0** [comment]
I've edited the source on Gizra.com and looks in this way:
download

**Comment by amitaibu** [comment]
No, sorry, the background looks too bad. We'll need another one.

**Comment by DavidBronfen** [comment]
@alvar0hurtad0 
There is to much `glow` effect on your contour silhouette.
There is a color cast on the background (white balance needs more touch up)

My advice is to take a new photo on a real black / dark gray background with a good camera, maybe you can try to use a tripod in order to get a sharp photo.

**Comment by alvar0hurtad0** [comment]
Ok,

I think better go to a professional photographer to take the photo, I used
a tripod, a not bad camera (not professional but almost reflex) with a good
quality lens (35mm 1.8).

I'll try to go and take the picture this week.

**Comment by DavidBronfen** [comment]
@alvar0hurtad0 
> I used a tripod, a not bad camera (not professional but almost reflex) with a good quality lens (35mm 1.8).

Try to set the lens to autofocus on your head (eye or cheek not the nose) / chest area.
The shutter speed shouldn't be lower than 1/60 if possible set it to 1/125.
Try to stand in front of a natural light source (window or door).

(I'm trying to find for you a solution before you'll go to spend your money :wink:)

**Pull request merged**
