### PR TITLE
Post: Elm From a Business Perspective

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
I still need to add a thumb image, but this can already be reviewed.

**Comment by IshaDakota** [comment]
I'll read - having trouble focusing on other things due to the political situation.

**Comment by amitaibu** [comment]
👍 

I assure you I have successfully resisted adding any remark about the above mentioned political situation, so it's a safe place for you :)

**Comment by IshaDakota** [comment]
Political situation aside - great post. I was wondering if you would have a response to that piece.

If you want to play on our misery, you could make the title - Elm From a Business Perspective: Making Development Great Again !

Be sure to read through, in the spirit of Elm, I made some "opinionated" style edits.

**Comment by amitaibu** [comment]
Thanks. I've added a thumb, and doing final read before deploy

**Comment by amitaibu** [comment]
Deployed -- http://www.gizra.com/content/elm-business-perspective/

**Comment by amitaibu** [comment]
@IshaDakota There's nothing like watching our google analytics after an Elm post 🍷

**Pull request merged**
