### PR TITLE
Add apply link & remove dots from images caption.

### PR DESCRIPTION
**Pull request by nader77**
#585

1. 
it_s_not_a_wonder__women_

2.
it_s_not_a_wonder__women_

3.
it_s_not_a_wonder__women_

@OritGeron Good ? anymore changes ?

/cc @RachelBaram

### CODE REVIEW

**Comment by OritGeron** [comment]
@nader77 That's awesome.  
Please add additional space in the wording below -

it_s_not_a_wonder__women_

**Comment by nader77** [comment]
it_s_not_a_wonder__women_

**Comment by nader77** [comment]
@OritGeron Anything else ?

**Comment by nader77** [comment]
@ordavidil please review.

**Comment by nader77** [comment]
10x man.

**Pull request merged**
