### PR TITLE
[Blog post] My new insecurity: Working without automatic tests.

### PR DESCRIPTION
**Pull request by nedSaf**

### CODE REVIEW

**Comment by RachelBaram** [comment]
@nedSaf Please finish this up with a thumb.

**Comment by nedSaf** [comment]
@IshaDakota @RachelBaram Added

gizra-post

**Comment by nedSaf** [comment]
@RachelBaram Added your edits, please refresh the code and check it out :)

**Comment by IshaDakota** [comment]
@nedSaf 

I added an image (that I also used in a past post and some headers to break it up a bit.

If you approve, I'll publish tomorrow (or you can if you want it to hit earlier in Israel).


fireshot capture 491 - my new insecurity_ working without au_ - http___localhost_3000_content_work

**Comment by nedSaf** [comment]
@IshaDakota Thanks, looks much better, you can publish whenever you want :)

**Comment by IshaDakota** [comment]
Thanks @nedSaf - may it be as popular as the last one!

**Comment by nedSaf** [comment]
Great, @IshaDakota @RachelBaram  Thanks for all the help.

**Pull request merged**
