### PR TITLE
WIP :blog post - phone booth

### PR DESCRIPTION
**Pull request by kazabooboo**

### CODE REVIEW

**Comment by RachelBaram** [comment]
@kazabooboo Cleaning up the queue... what is the status of this? Should this be closed?

**Comment by kazabooboo** [comment]
@RachelBaram please keep it open. it is a blog post I have been working on, thanks

**Comment by kazabooboo** [comment]
@amitaibu @RachelBaram  ( I am pretty sure that  I am doing it correctly) . Text for blog post. @IshaDakota already edited it 
Good [picture](http://freeversephotography.com/freeversephotoblog/wp-content/uploads/2013/06/MG_3392_stitch.jpg) 
Tomorrow morning , I will take a picture of my desk. Looks better with natural light. 

If you can't see the code - the text can be found here 
[phonebooth.txt](https://github.com/Gizra/gizra.com/files/581990/phonebooth.txt)

**Comment by RachelBaram** [comment]
@IshaDakota Pressing on the pencil does not work - nothing happens. Can you think of a reason I don't have access to editing?

**Comment by IshaDakota** [comment]
@kazabooboo made this a patch from his account... which you don't have access to, let me see here...

**Pull request closed without merging**
