### PR TITLE
Proposed homepage

### PR DESCRIPTION
**Pull request by adamhstewart**
image

### CODE REVIEW

**Comment by IshaDakota** [comment]
had to merge in #560 because couldn't see it separately.

Not certain about the font, but definitely a serif/sans serif pairing.

**Comment by IshaDakota** [comment]
stories menu (w/o colors theme)

design___web_development___gizra

**Comment by amitaibu** [comment]
Thanks.

Tablet is slightly broken.

design___web_development___gizra

Also, I prefer the existing version of the stories title, with the colored top border, which appears on the page as-well

**Comment by IshaDakota** [comment]
Added a line height to tagline:
design___web_development___gizra

reverted stories menu
design___web_development___gizra

although, I don't think these colors provide much consistency with the rest of the site... looks like google.

**Pull request closed without merging**
