### PR TITLE
Homepage Redux

### PR DESCRIPTION
**Pull request by IshaDakota**
image

### CODE REVIEW

**Comment by IshaDakota** [comment]
@RachelBaram Here's a start at the header portion.

What you can't see in a static image is a really cool moving clouds feature inspired by (shamelessly lifted from) [here](http://franperez.me/).

You can feel free to wordsmith - I'm going to work on the featured work section right below this.

**Comment by IshaDakota** [comment]
moving-clouds

**Comment by RachelBaram** [comment]
@IshaDakota My thoughts so far:

- It's great that you moved the text to the center. I think we need to separate the logo and menu from the rest of the page. [Palantir ](https://www.palantir.net/) does it subtly while others create a very distinct block like [Chapterthree](https://www.chapterthree.com/). If our page feels dark, [Phase2's](https://www.phase2technology.com/) solution can help lighten things up.

- The clouds are cool. ;)

- The text is shorter and I like that.

- Happy the arrow is in the middle. It always felt weird that it was on the side while the rest were in the middle.

- The About Story. Where to put it? It is quirky and for curious people, it gives insight to Gizra's personality. 

- Drupal expertise. I don't think we need to say it in the header portion. However, I think it should be very clear, very quickly that this is the main technology we spearhead. For example Phase2 below the fold has a Drupal8 resource center, Palantir's homepage case study talks about headless Drupal. Do you have any ideas? Maybe shorten our About Us and make sure that Drupal is easily seen? Maybe mention it in the project descriptions? I am starting to also look at how we provide more information about our contributions - I like how Phase2 does it with a Community page.

Looking forward to seeing the featured work section.

**Comment by IshaDakota** [comment]
Just a draft:
image

**Comment by IshaDakota** [comment]
Spotlight section draft:
image

**Comment by IshaDakota** [comment]
> I think we need to separate the logo and menu from the rest of the page. 

Let's do this in another issue - this one is getting pretty crowded.

> The About Story. Where to put it? 

I don't know.

> Drupal expertise. 

This is solved by the spotlight section which names Drupal and "complex content management."

**Comment by IshaDakota** [comment]
@RachelBaram thoughts on the above draft?

**Comment by RachelBaram** [comment]
How does it look with the section above it? Trying to understand the
proportions between the logo and "Gizra way at work".

**Comment by IshaDakota** [comment]
Because of the 100vh on each section, you would never see the two sections on the screen at the same time - so the full screenshot is deceiving in that regard

homepage

**Comment by RachelBaram** [comment]
@IshaDakota Almost there.  It looks great and this redux has solves some immediate required fixes. My thoughts:
- logo/menu area - I opened a separate issue #542 
- About Story ("Read our About Story — It's different."). It has to stay. Some possible places to put it:
1. in the box located under the slogan - at the end in its own row, centered - my preference
2. in the about us section - at the end, one space after the paragraph, aligned left
- "The Gizra Way at Work" section
1. the logo between the blue text looks too "cartoonish." It is a great idea to show our logo again but it does not work there. I would keep it all blue font.
2. There needs to be a button/link to the project portfolio page - something like "More Gizra projects"
3. It may be too busy but this is also a great place for a call to action "Let's talk about your project"
4. I don't feel strongly about this and we may need to consider this later: Is there any nice way to show the list of logo's in the above the fold area? At first glance, people will see brands they know. That is powerful. One scroll away (as it is now) is good enough if this is too much effort.

**Comment by IshaDakota** [comment]
image

> About Story

Done - but I have some reservations about highlighting a page that has over 50% dropoff rate.

> the logo between the blue text looks too "cartoonish."

I just removed the title here altogether - it's intuitive that this is our work and it was looking to crowded. I like this a lot better.

> There needs to be a button/link to the project portfolio page - something like "More Gizra projects"
> It may be too busy but this is also a great place for a call to action "Let's talk about your project"

I added both of these in a way that is consistent with the above - I think it works

> : Is there any nice way to show the list of logo's in the above the fold area?

Don;t think this is a good idea - and falls into the "above the fold" trap.

**Comment by amitaibu** [comment]
> Done - but I have some reservations about highlighting a page that has over 50% dropoff rate.

If you want to remove it from the homepage/ current location, I have no objection. It's between you and Rachel.

**Comment by IshaDakota** [comment]
> If you want to remove it 

No. It's probably my favorite content on the site. I want to figure out a way so it doesn't seem like the user is leaving the site. I think that explains the drop off.

**Comment by RachelBaram** [comment]
@IshaDakota 

> **I want to figure out a way so it doesn't seem like the user is leaving the site. I think that explains the drop off.**

I agree. It may also be tl dr situation. I know that Amitai likes how it looks now but I would break it up a little to help the reader along.

The changes you made look good. Let's do it - excited to move forward with the next phase.

**Comment by IshaDakota** [comment]
@RachelBaram please do a final review at: http://gizra.mlizard.com. We never really edited the tagline or subtitle.

@amitaibu If you have a chance, there's a lot of changes here - a code review would probably be warranted.

**Comment by amitaibu** [comment]
> @amitaibu If you have a chance, there's a lot of changes here - a code review would probably be warranted.

@DavidBronfen please peer review the PR

**Comment by DavidBronfen** [comment]
@IshaDakota @amitaibu 
Looks good beside the `app/index.html` conflict.

**Comment by IshaDakota** [comment]
Thanks @DavidBronfen ! (one note: check for abandoned code. I removed a carousel which meant we can remove all the accompanying css as well.)

@RachelBaram you can see mobile fixes [here](http://gizra.mlizard.com/).

Please give an indication here that you have reviewed and I'll merge/deploy.

**Comment by RachelBaram** [comment]
@IshaDakota I started working on shortening the text and found that it is not here nor there. Making the home page more simple will be about deciding where and how the content will be presented.  This will happen next round.

Only one small input - on mobile, there needs to be a little more space between the projects. It takes an extra glance to understand that the titles go with the image above and not the one below.

It sometimes may feel we are doing it in baby steps, but the website is moving in the right direction. Thank you!

**Comment by DavidBronfen** [comment]
@IshaDakota 
Yes i saw that you removed all the css that belongs to the carousel in the `_testimonials.scss` file.
Do i need to check in other files if there is another css properties that belongs to that carousel?

**Comment by IshaDakota** [comment]
space between projects:
image

@DavidBronfen I think we're good - thanks!

**Comment by IshaDakota** [comment]
merged and deployed - hooray.

**Comment by amitaibu** [comment]
Nice work, clouds and all!

I guess next thing is completely re-writing the site. But that's for 2017 😜

**Comment by amitaibu** [comment]
And of course extra points to all for the fact I had zero involvement in this effort!

**Pull request merged**
