### PR TITLE
Set two rows of blog teasers on home page and make height static

### PR DESCRIPTION
**Pull request by IshaDakota**
#486 & #470

This just adds 2 more posts and sets the height of that section to 1000px on every desktop-width.

This is a little hard to demo on a 13'' Macbook, so maybe @guytepper or @DavidKohav  , you want to pull it local?

fireshot capture 123 - design web development i gizra - http___0 0 0 0_9000_

### CODE REVIEW

**Comment by DavidKohav** [comment]
@IshaDakota - I checked it in local, looking grate.

**Comment by IshaDakota** [comment]
@RachelBaram I'll merge this if you have no objections.

@amitaibu not much code touched, so I'll do without a review unless you halt.

**Comment by amitaibu** [comment]
Feel free

**Comment by RachelBaram** [comment]
No objections.

**Pull request merged**
