### PR TITLE
Services page

### PR DESCRIPTION
**Pull request by IshaDakota**
#417 and #409

### CODE REVIEW

**Comment by IshaDakota** [comment]
very much WIP, and can't say I like where it's going.

fireshot capture 28 - services - http___0 0 0 0_9000_services_

**Comment by IshaDakota** [comment]
@RachelBaram As I'm working on this I'm wondering if it's necessary to have a full page for each service? It seems like a lot of work and without listing some of the core services, like Drupal/CMS, strategy, UX, etc... it will be incomplete.

see for instance: http://fourkitchens.com/what-we-do/#our-services

**Comment by RachelBaram** [comment]
I visualized something like this (text is not aligned and spacing is off but its just to give you an idea) as a landing page for services. I would like us to have individual pages for all the services - its  a great place to present more information including blogs and case studies with the appropriate tags and its great for SEO (we really suck at it so far). As we slowly build the services content we link it from this page.

The text on the landing page would be drafted according to what the design allows. What do you think?

services page

**Comment by IshaDakota** [comment]
@RachelBaram perfect.

so essentially we can leave out the "more" links and links in the body of the text, until the pages are created?

**Comment by RachelBaram** [comment]
Yes.

**Comment by IshaDakota** [comment]
@RachelBaram can you point me to this text so that I can use it instead of lorem ipsum?

**Comment by IshaDakota** [comment]
@RachelBaram never mind... got it at https://docs.google.com/document/d/1jBSRQlK-AmUsjF_KXWvuKQmEQYGy5VfWOjPL15Wj_LM/edit#heading=h.abq1oxt18yrr

**Comment by IshaDakota** [comment]
@RachelBaram haha, actually, no, that's not all of it.

**Comment by RachelBaram** [comment]
I plan on taking this [text](https://docs.google.com/document/d/1dWVtfFUDRohtjlnjH6RBEN-NkoRl0eOLz1zbZLRyvmU/edit) and editing it down.

**Comment by IshaDakota** [comment]
That's the text that I used, but it only has the first three "services"

**Comment by IshaDakota** [comment]
WIP status:

fireshot capture 32 - services - http___0 0 0 0_9000_services_

**Comment by IshaDakota** [comment]
@amitaibu This is mostly ready for review - waiting for text from @RachelBaram .

It should wait for #423 to be deployed, then will require a re-roll.

fireshot capture 33 - services - http___0 0 0 0_9000_services_

**Comment by IshaDakota** [comment]
@RachelBaram a few points:

- I think this shows the ideal text length of the services - pretty short, but maximum readability.
- Do you think maybe "Services We Provide"... better grammar, less awkward.
- If you can get someone to pull the branch into a development environment, you'll get a better feel for it.

**Comment by RachelBaram** [comment]
@IshaDakota some points:

- I like the shorter text.

- "Services We Provide" is much better... the screenshot I provided was with filler text instead of Lorem ipsum (I have no allegiance to any of it). We are including two sections that are not really services (Gizra Alpha and Across Industries) so if you have an idea of a title that would be more inclusive of this... all the better. Otherwise, we can change this later if needed.

- The text for the bottom three services can be found [here](https://docs.google.com/document/d/19e1tytcBkxQEeS8d22-UnIe9O1yAvY4EOr4OAASm9F8/edit).

- A Gizra Alpha section is also required. #217

**Comment by IshaDakota** [comment]
@amitaibu  This is probably ready to go.

fireshot capture 35 - services - http___0 0 0 0_9000_services_

**Comment by amitaibu** [comment]
Seems to be a big margin-bottom on the elements, can you please verify:

services

**Comment by IshaDakota** [comment]
@amitaibu That's not a bug, it's a feature.

```
#services-page, #strengths-page, #cases-page {
   min-height: 100vh;
}
```
sets the height of the dive to the height of the display. It creates the illusion of a slide show (which I like). On the larger displays (27inch thunderbolt display, I assume), there get's to be a lot of space at the bottom.

Possible solutions:
- Space is nice, leave it.
- Throw a "scroll to div" pager down there so that it's clear there is more content.
- Center the text vertically 
- Create a different layout for large format displays
- Set a max-height also.

**Comment by IshaDakota** [comment]
@amitaibu I centered the text vertically using flexbox - unsupported browsers will render with space at the bottom. Also matched the larger font format (which helps this as well). 

@RachelBaram check text edits and format changes. per your approval - ready for review.

fireshot capture 49 - services - http___0 0 0 0_9000_services_

**Comment by amitaibu** [comment]
Assigned to @RachelBaram for text review

**Comment by RachelBaram** [comment]
Text Review: 
For the Gizra alpha Products section: at the end of the sentence - take out the "be" before "address."

Let's get this out. I don't see this content as final and will shoot off improvements in time. For now, it is good enough.

**Comment by IshaDakota** [comment]
@amitaibu Made a fix to vertical spacing, ready for your review.

**Comment by amitaibu** [comment]
Thanks!

**Pull request merged**
