### PR TITLE
Adding Value Blog

### PR DESCRIPTION
**Pull request by RachelBaram**

### CODE REVIEW

**Comment by RachelBaram** [comment]
classic-vintage-filter-camera-yashica-photography-711794

**Comment by RachelBaram** [comment]
@IshaDakota Here are the pictures and their captions:

lighthouse-at-sunset_4460x4460
The business goal - the beacon that guides every step. Photo by Justin Pauley.

Not sure if this code (see in edit mode) is useful for the credit:  Photo by <a href="https://burst.shopify.com/@jspauley?utm_campaign=photo_credit&amp;utm_content=High+Res+Lighthouse+At+Sunset+Picture+%E2%80%94+Free+Images&amp;utm_medium=referral&amp;utm_source=credit">Justin Pauley</a> from <a href="https://burst.shopify.com/bridge?utm_campaign=photo_credit&amp;utm_content=High+Res+Lighthouse+At+Sunset+Picture+%E2%80%94+Free+Images&amp;utm_medium=referral&amp;utm_source=credit">Burst</a>

living-on-the-edge-844873_1280
Building on the edge is not good for business.

**Comment by IshaDakota** [comment]
@RachelBaram check my edits
fireshot capture 502 - stripped down to the essence_ _ - http___localhost_3000_content_adding-value_

**Comment by RachelBaram** [comment]
Cool. Thanks!

**Comment by IshaDakota** [comment]
@RachelBaram ^^ certainly that's not permissions free?

**Comment by RachelBaram** [comment]
Yeah. That is a problem.

**Comment by IshaDakota** [comment]
merged && deployed - thank you @RachelBaram !!

**Pull request merged**
