### PR TITLE
Inbox Simulation Post

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by IshaDakota** [comment]
This is probably ready for review - @amitaibu can you review for tech and @RachelBaram for grammar.

**Comment by amitaibu** [comment]
Awesome stuff! Few comments to consider:

1. I think it's worth to invest a few more minutes in the `admin-prototype.jpg` image an replace the "yada yada" with more realistic comment. You can also make the last "Submit" button `primary`.
1. Your call, just and idea, but I think that with adding a few words on Drupal, it can fit to "Planet Drupal". A way It could be done is something like: We invested only in the front end, but if we want to hook it to a backend Drupal can help us with the same MVP mindset. Slap a few modules together, create the nodes, and expose them with RESTful. Which means you get to have a shared `model` between the frontend and the backend.

**Comment by IshaDakota** [comment]
> I think it's worth to invest a few more minutes in the `admin-prototype.jpg` image an replace the "yada yada" with more realistic comment.

Don't you think it demonstrates the "sketchy" aspect of that task? Particularly because we didn't even use that page.

> but I think that with adding a few words on Drupal, 

I think that's a good idea - does this seem forced?

##What We Didn't Do
In this case, we ignored all other features, even how to permanently store the data -- just a simple single page application that shows a realistic inbox with a few features. Ultimately, any LMS is a content management system, and in CMS tasks, our framework of choice is Drupal. If we wanted to demonstrate backend capability, Drupal could help us with the same MVP mindset. Just put a few modules together, create the nodes, and expose them with RESTful, and you get to a shared `model` between the frontend and the backend.

But that's more than we wanted to do here. I never even got my admin screen - there wasn't enough time, and there's other stuff to do.

**Comment by amitaibu** [comment]
Ok, I think that the Drupal part is weakening the post, so maybe we should revert it. Sorry for the bad advice :/

After that,  I think it's ready - care to deploy it?

**Comment by amitaibu** [comment]
(that is, without the `Planet-Drupal` tags)

**Comment by IshaDakota** [comment]
thanks! merged.

**Pull request merged**
