### PR TITLE
Typography and CSS cleanup

### PR DESCRIPTION
**Pull request by IshaDakota**
#419

### CODE REVIEW

**Comment by IshaDakota** [comment]
#419 
This PR is mostly typography consistency and CSS cleanup. 

Some slightly more significant changes were made to the menu:

fireshot capture 60 - elm web development company - gizra - http___0 0 0 0_9000_services_elm_

Shortened menu titles so that the menu does not creep so far to the left (and cover the balloon). This can be reverted if not desirable.

...And to the service pages to get them more in line with the other page changes.

fireshot capture 61 - elm web development company - gizra - http___0 0 0 0_9000_services_elm_

hr

The remaining changes are consistency and code cleanup.

**Comment by IshaDakota** [comment]
@RachelBaram check header

@amitaibu check code.

**Comment by IshaDakota** [comment]
And optimized the header images as compressed JPG - no quality loss but saves 1MB on homepage alone.

**Comment by RachelBaram** [comment]
Header looks good. I was thinking of recommending as such and you beat me to the punch. You are awesome.

**Comment by IshaDakota** [comment]
great - just for review by @amitaibu

**Comment by amitaibu** [comment]
❤️

**Comment by amitaibu** [comment]
Wonderful!

btw, if you are up for the challenge, I'd love getting read of bootstrap and move from the old school `float` oriented grids to flexbox. So it will become properly responsive on all devices, as anyway we don't care about IE9 and downwards

**Comment by DavidKohav** [comment]
http://flexboxgrid.com/

**Pull request merged**
