### PR TITLE
WIP: Blog Descriptions

### PR DESCRIPTION
**Pull request by RachelBaram**
Adding blog descriptions to past blogs. For issue #508.

### CODE REVIEW

**Comment by IshaDakota** [comment]
@RachelBaram How's this project going? I don't think we need to do all of our posts - maybe just back 20 the beginning of 2016?

**Comment by RachelBaram** [comment]
@IshaDakota I did a few. I think this cutoff helps make this a more approachable task. I have been finding it difficult writing descriptions for the technical posts.

**Comment by IshaDakota** [comment]
@RachelBaram for technical posts, you can either flag them for someone else, or simply take the first sentence of the post... that's better than nothing.

**Comment by RachelBaram** [comment]
@IshaDakota 2016 blog descriptions complete.

**Comment by RachelBaram** [comment]
Oops.  Sorry.

**Pull request merged**
