### PR TITLE
Changes to team page layout

### PR DESCRIPTION
**Pull request by IshaDakota**
#413

### CODE REVIEW

**Comment by IshaDakota** [comment]
I kind of like the team page and the unique header there.

This apply the proposed header style, tightens it up a bit, and makes the container on the images fluid.

fireshot capture 27 - team i gizra - http___0 0 0 0_9000_team_

**Comment by amitaibu** [comment]
Ready for review?

**Comment by IshaDakota** [comment]
Yes per @RachelBaram 's approval.

**Comment by RachelBaram** [comment]
I am less of a fan of this page header. Cool with the stock photo but "The Team" font is inconsistent. Maybe capitalize it so it looks like the Blog and Services pages? You won't be able to make it blue since the text sits on the header and not below.

**Pull request closed without merging**
