### PR TITLE
WIP: Adding access token blog post.

### PR DESCRIPTION
**Pull request by RoySegall**

### CODE REVIEW

**Comment by RachelBaram** [comment]
@RoySegall Are you still planning on moving forward with this? If not, please close it. ;)

**Comment by RoySegall** [comment]
Ammm... We stopped because we felt the access token isn't secure enough and we tried something. Don't remember what.

@amitaibu Do you remember what we did eventually?

**Comment by amitaibu** [comment]
So it helped others understaind this, so lets revive this post. @RoySegall Can you please go over it, to see it's still correct

**Comment by RoySegall** [comment]
Nothing changed since then but i'll give it a second look.

**Comment by RoySegall** [comment]
@amitaibu Except for the small semantic change i need to do this one looks OK. I'll create a new PR and close this one.

**Comment by RoySegall** [comment]
Closing.

**Pull request closed without merging**
