### PR TITLE
WIP: Homepage Redesign

### PR DESCRIPTION
**Pull request by IshaDakota**
image

### CODE REVIEW

**Comment by IshaDakota** [comment]
image

cc/ @RachelBaram

**Comment by RachelBaram** [comment]
@IshaDakota Yes!

**Comment by amitaibu** [comment]
@IshaDakota thanks for working on this!

There are some points about the homepage I'd like to discuss - ping when around :)

**Comment by IshaDakota** [comment]
status:

fireshot capture 525 - web strategy design development i gizra - http___localhost_3000_

**Comment by IshaDakota** [comment]
merging to feature branch

**Pull request merged**
