### PR TITLE
Remove soft box from post teasers

### PR DESCRIPTION
**Pull request by IshaDakota**
#418 
 
Or... a better way to fix post teasers: take away the "soft box."

Hint: They're ugly.

I prefer this to #421 

fireshot capture 34 - gizra s blog - http___0 0 0 0_9000_blog_

### CODE REVIEW

**Comment by amitaibu** [comment]
I won't argue that the boxes are "pretty", but I think without it, it looks like some CSS mistake. I'm in favor of keeping them.

**Comment by IshaDakota** [comment]
@RachelBaram please weigh in on the great post teaser debate: this or #421. 

If we implement #421, we need to go through titles to be sure they are not more than 2 lines.

**Comment by RachelBaram** [comment]
I think we should keep the boxes and change the titles.  A quick glance... there are about 10 titles to be changed.

**Comment by IshaDakota** [comment]
@RachelBaram It's competing OCDs - I obsess against solutions that box you in (literally) to preset content lengths. You and @amitaibu win this round!

**Comment by RachelBaram** [comment]
;) Totally get it. I thought that limiting the title length will support good title practice by limiting "title laziness" of trying to say too much in a short sentence... yes I am guilty of this as well (look who's blog name needs to be changed first.)

**Pull request closed without merging**
