### PR TITLE
pictures from Hand-On with ELM blog post.

### PR DESCRIPTION
**Pull request by nader77**
#466

### CODE REVIEW

**Comment by nader77** [comment]
pictures_from_hands-on_with_elm_-_tel_aviv


Preview:
gizra_s_blog

**Comment by nader77** [comment]
@amitaibu Please review.

/cc @RachelBaram

**Comment by amitaibu** [comment]
Were is the actually content? 😉 

It's a post no one will really care about. Just a bunch of images of strangers and some tweet that doesn't mean too much. 

If there was a post it should be about what we actually learned, the [steps](https://github.com/Gizra/elm-tlv3) we took, etc'. In other words, it should be a no BS post

As for the images, I'd just link to some google photos account that has the images.

**Comment by amitaibu** [comment]
(but thanks of course for working on it)

**Comment by nader77** [comment]
@RachelBaram Should I close this as not relevant ? I'll upload the pictures to FB.

**Comment by RachelBaram** [comment]
Yes.

**Pull request closed without merging**
