### PR TITLE
Employee names and title alignment.

### PR DESCRIPTION
**Pull request by DavidBronfen**
#528

### CODE REVIEW

**Comment by DavidBronfen** [comment]
image

**Comment by RachelBaram** [comment]
@IshaDakota This is the lowest required resources solution that we found. What do you say?

**Comment by IshaDakota** [comment]
@DavidBronfen @RachelBaram yeah, I think this is fine... do you want to look into trying a [flexbox magic vertical centering solution](https://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/)?

**Comment by DavidBronfen** [comment]
@RachelBaram @IshaDakota I'll try to set it flex when i'll have a free hour. Thanks for the advice :)

**Comment by RachelBaram** [comment]
Can we deploy in the meantime so at least it gets fixed?

**Comment by DavidBronfen** [comment]
@IshaDakota @RachelBaram 
Hey, this is the result with the flexbox magic:

Desktop:
selection_002


Tablet:
selection_003

Mobile:
selection_006

Let me know what is your opinion.

**Comment by IshaDakota** [comment]
@DavidBronfen it looks good... push the commit?

**Comment by DavidBronfen** [comment]
@IshaDakota Done.

**Comment by RachelBaram** [comment]
@amitaibu Please review.

**Comment by amitaibu** [comment]
@RachelBaram, form now on @IshaDakota is now the official person to assign it to him. He's doing a better job than me with the site 😄

**Comment by IshaDakota** [comment]
alrighty then... 

@DavidBronfen small nesting nitpick on the css (see [commit](https://github.com/Gizra/gizra.com/pull/531/commits/98fbb75ac0e4136a46d2a45eff1377249e504be9)) and `align-items: center` is not necessary (in fact breaks the icon display - see [commit](https://github.com/Gizra/gizra.com/pull/531/commits/052728b22a6459c77759d33418923a7bacc72468))

**Comment by IshaDakota** [comment]
@amitaibu one question before merging... is there a particular reason for:

````html
              <li class="hidden-xs">
                <a href="mailto:{{ member.email }}">
                  <img src="/images/team/at.png" alt="email">
                </a>
              </li>
````

and

````html
                <li class="hidden-xs">
                  <a target="_blank" href="https://twitter.com/{{ member.twitter }}"><img src="/images/team/twitter.png" alt="twitter"></a>
                </li>
````
three icons fit across all the way down to 350px - seems like it would be good to have email and twitter on mobile especially.

**Comment by amitaibu** [comment]
no reason.

**Comment by IshaDakota** [comment]
Changed icons to font icons wile I was at it as well.

image

**Comment by IshaDakota** [comment]
merged and deployed - thanks @DavidBronfen !

**Pull request merged**
