### PR TITLE
Fit page

### PR DESCRIPTION
**Pull request by IshaDakota**
Draft with some dummy text:
fireshot capture 73 - strategy and consulting - http___0 0 0 0_9000_fit_

### CODE REVIEW

**Comment by amitaibu** [comment]
I actually even like most of text 😄

**Comment by IshaDakota** [comment]
A cheeky background image/message?

fireshot capture 74 - strategy and consulting - http___0 0 0 0_9000_fit_

**Comment by IshaDakota** [comment]
with icons and some new text:

fireshot capture 75 - strategy and consulting - http___0 0 0 0_9000_fit_

**Comment by amitaibu** [comment]
I think the background text doesn't add here, also makes the main text less readable

**Comment by IshaDakota** [comment]
> I think the background text doesn't add here, also makes the main text less readable

fair enough. do you like the idea of an image at all?

**Comment by amitaibu** [comment]
Yes, an image as a banner might fit. Although it could also be as a follow up.

btw, do you have an idea on how to add this page to the navbar (`do we fit each other` seems way too long)

**Comment by IshaDakota** [comment]
> do you have an idea on how to add this page to the navbar
ideas:
- collaborate
- do we fit?
- fit with us
- make it fit (ew?)
- work with us
- fit check

**Comment by amitaibu** [comment]
since the page is quite different, maybe the navabar item can be a bit more teasing, examples:

* Gizra-o-meter
* Not for all
* Maybe yes, Maybe no
* Truth or dare

**Comment by RachelBaram** [comment]
Would something like this be too weird? Not sure if I really hate it or maybe like it. Problematic in the hamburger menu?

screenclip

**Comment by IshaDakota** [comment]
Not certain about the image.

fireshot capture 76 - strategy and consulting - http___0 0 0 0_9000_fit_

**Comment by RachelBaram** [comment]
The image does not 'fit'  the page very well. :p I like the idea because it gives a different feel than the rest of our pages. How about shrinking it and setting it to the side of only the first paragraph and let the second paragraph fill the width again.

**Comment by DavidKohav** [comment]
Hi all :),

You can do tree things to make it better from my opine 
1. align the image with the text (You've been down...)
2. float left the image and  align the image with the text (You've been down...)
3. have a more high-line to the big text.

have a nice day

**Comment by IshaDakota** [comment]
> The image does not 'fit' the page very well.

I think the problem is with the image itself - its amateur and unbalanced. We should either get someone to draw a better one, find one, or leave it out.

**Comment by amitaibu** [comment]
IMO leave out for now

**Comment by IshaDakota** [comment]
fireshot capture 78 - strategy and consulting - http___0 0 0 0_9000_fit_

**Comment by RachelBaram** [comment]
@amitaibu For your review.

**Comment by amitaibu** [comment]
Awesome stuff, thanks!
deployed.

**Pull request merged**
