### PR TITLE
Added property to the guid

### PR DESCRIPTION
**Pull request by DavidKohav**
#517

### CODE REVIEW

**Comment by DavidKohav** [comment]
@bricel -I did the PR, please check and merge.

**Comment by DavidKohav** [comment]
selection_064

**Comment by RachelBaram** [comment]
@amitaibu Can this be merged?

**Comment by amitaibu** [comment]
@bricel ^^

**Comment by bricel** [comment]
We need to test this.

**Comment by IshaDakota** [comment]
needs deploy?

**Comment by bricel** [comment]
yes please.

**Pull request merged**
