### PR TITLE
Properly set metatags for SEO and social media

### PR DESCRIPTION
**Pull request by IshaDakota**
This sets metatags to what (I believe) are minimal best practice for SEO and social media sharing.

- sets article og:title if it exists  (otherwise sets to site title)
- sets description and og:description, if it exists.;
- if descriptions exists, also sets up twitter summary card
- sets og:image if a thumbnail image exists.

This is more about setting up minimal metatag standards rather than creating a test for at as #469 suggests.

### CODE REVIEW

**Comment by IshaDakota** [comment]
@RachelBaram take a look... can't really test without putting in a publicly accessible environment.

https://cards-dev.twitter.com/validator
and

https://developers.facebook.com/tools/debug/

are good tools to check social sharing

**Comment by IshaDakota** [comment]
@amitaibu can you review this. If you deploy, it may be worth testing a post against the validators above.

**Comment by amitaibu** [comment]
@bricel you know this area better than me - can you give it a look please.

**Comment by bricel** [comment]
Looks ok merging.

**Pull request merged**
