### PR TITLE
Comment unnecessary placeholders (for now)

### PR DESCRIPTION
**Pull request by DavidBronfen**
#501

### CODE REVIEW

**Comment by DavidKohav** [comment]
merged!

**Comment by amitaibu** [comment]
No, please revert

**Comment by amitaibu** [comment]
We don't comment out code, we completely remove it. In this case just leave it, as this whole page will need some work.

**Comment by DavidKohav** [comment]
Revert Done.
selection_021

To be sure, Live the placeholders and not remove them?

selection_022

**Pull request closed without merging**
