### PR TITLE
Project slider & page

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by IshaDakota** [comment]
fireshot capture 84 - google hangouts_ - https___hangouts google com_hangou

**Comment by IshaDakota** [comment]
fireshot capture 87 - services - http___0 0 0 0_9000_services_
fireshot capture 86 - strategy and consulting - http___0 0 0 0_9000_projects_

**Comment by IshaDakota** [comment]
With screenshots:
fireshot capture 92 - strategy and consulting - http___0 0 0 0_9000_projects_

**Comment by IshaDakota** [comment]
Read the case study:
fireshot capture 99 - project portfolio - http___0 0 0 0_9000_projects_

**Comment by IshaDakota** [comment]
larger headers:
fireshot capture 102 - project portfolio - http___0 0 0 0_9000_projects_

**Comment by IshaDakota** [comment]
@RachelBaram this is ready for your review.

**Comment by RachelBaram** [comment]
I like this way better. It also gives us room to add 'stuff' on the left. Maybe tags describing the type of work  (titles listed in services page) and technology (Drupal modules, Elm) used, Industry, etc. The button to case study works well!

**Comment by IshaDakota** [comment]
@niryariv check out the additions of OpenTABA and Negawatt.

@RachelBaram maybe once over for proofreading

@amitaibu  otherwise ready for review.

fireshot capture 105 - project portfolio - http___0 0 0 0_9000_projects_

**Comment by amitaibu** [comment]
Can you convert images to jpg and optimize them (imageoptim for mac)

**Comment by IshaDakota** [comment]
You lose alpha-transparency on the shadow, but on white background you can't tell. I left PNGs committed so we have them in case we ever change backgrounds.

**Comment by RachelBaram** [comment]
@IshaDakota Done proofreading.

**Comment by niryariv** [comment]
@IshaDakota re:OpenTABA - mentioning it to clients etc is fine, but we can't really put it on the site as an Alpha project. Outside of myself there's been several volunteers working on it (and a civil planner who co-created it), they wouldn't be pleased to see their work being used for our business goals.

**Comment by IshaDakota** [comment]
Got it. Wasn't aware of the makeup of the project.

**Comment by amitaibu** [comment]
> I left PNGs committed so we have them in case we ever change backgrounds.

It's better to remove them - we always keep only the used stuff on the repo. Since it's git, you will still have them in the history.

**Comment by IshaDakota** [comment]
> Since it's git, you will still have them in the history.

good point.

**Comment by amitaibu** [comment]
Slider on `/services` seems to be broken

services

**Comment by amitaibu** [comment]
Thanks!

**Comment by amitaibu** [comment]
deplyed

**Pull request merged**
