### PR TITLE
Case study page based on blog page.

### PR DESCRIPTION
**Pull request by IshaDakota**
fireshot capture 44 - one database to rule them all - http___0 0 0 0_9000_case-studies_openscholar_

### CODE REVIEW

**Comment by IshaDakota** [comment]
@RachelBaram please review

**Comment by IshaDakota** [comment]
probably a good idea to get this out because the blog update broke it on the live site.

fireshot capture 51 - one database to rule them all - http___0 0 0 0_9000_case-studies_openscholar_

**Comment by amitaibu** [comment]
👍 can you please merge & deploy

**Comment by IshaDakota** [comment]
merged

**Pull request merged**
