### PR TITLE
Fix the config yml for members

### PR DESCRIPTION
**Pull request by DavidKohav**
#482

### CODE REVIEW

**Comment by DavidKohav** [comment]
team gizra

**Comment by DavidKohav** [comment]
Didn't find the problem why the Behat blog test field in Travis servers.
Open new issue for that.

**Comment by amitaibu** [comment]
Thanks. I can't check it now, but if it fixes the problem please deploy. If there are other such urgent issues please feel free to merge and deploy (no need to assign to me while I'm away).

**Comment by DavidKohav** [comment]
Ok , 10X

**Comment by amitaibu** [comment]
Seems it's still wasn't merged and deployed :/ As indicated in above comment, please don't wait for me to do it.

This time, I've deployed.

**Pull request closed without merging**
