### PR TITLE
Strategy page

### PR DESCRIPTION
**Pull request by IshaDakota**
fireshot capture 72 - strategy and consulting - http___0 0 0 0_9000_services_strategy-consulting_

### CODE REVIEW

**Comment by IshaDakota** [comment]
@RachelBaram These are with the edits - I made a fe more, so please review.

Also, I like the idea of the background image on pages like this to add some visual interest. But I'm not committed to it  if you don't like.

fireshot capture 106 - consultation and partnership - http___0 0 0 0_9000_services_partnership_

**Comment by RachelBaram** [comment]
@IshaDakota 

- I also like the idea of a visual to help distinguish between the pages since (for the sake of consistency) they all look the same. My issue with this background image is that it makes the text difficult to read. Unfortunately, I don't have an alternative suggestion for a visual that does not 'bother' the readability of the text. Hmm.
- Reviewed the text... looks good.
- We also need to change our services page (change title of strategy&consulting, maybe the descriptive text, and link it to this page)

**Comment by IshaDakota** [comment]
> My issue with this background image is that it makes the text difficult to read.
I don't really find it that difficult to read. The problem with an image on it's own is that we would need to find/create something really unique.

> and link it to this page
How's this?
fireshot capture 107 - services - http___0 0 0 0_9000_services_

**Comment by RachelBaram** [comment]
@IshaDakota I like the text change. Would people understand that if they want to read more about Consultation and Partnership, the "we can be your partner" is where they should go?  I try to take into account the lowest common denominator (or someone too busy/distracted to think twice).

**Comment by IshaDakota** [comment]
Yeah. I'm not sure on that. Do you envision these will be one to one (each
bucket goes to one page)? If so we could link the whole thing.... Or create
a "more" button.

**Comment by RachelBaram** [comment]
Yes. The goal is to expand each service one to one with a more detailed description along with relevant  projects, case studies, and blogs. Hence my goal of technology, industry, and service type tags on everything. I don't have an opinion about linking the whole thing vs. more button.

**Comment by IshaDakota** [comment]
@RachelBaram I thought about this a little, and I think the main problem is in short-term deployment - we don't yet have pages for all of the buckets here. How about this as a short term strategy: For now, let's link as they are are here (within the text), and then in the longer term (when all the pages are created), we can create a more universal and action-oriented linking scheme.

Re background image... your call.

**Comment by RachelBaram** [comment]
I am OK with that. We will create a universal linking system once the page content is ready. :)

**Comment by IshaDakota** [comment]
@RachelBaram need a final call on the background image, then this is ready for review.

**Comment by RachelBaram** [comment]
Let's skip the background image for now. Cool?

**Comment by IshaDakota** [comment]
@amitaibu ready for review.

**Comment by IshaDakota** [comment]
fireshot capture 110 - consultation and partnership - http___0 0 0 0_9000_services_partnership_

**Comment by RachelBaram** [comment]
@amitaibu I know you are super busy. Can we move forward without your review?

**Comment by amitaibu** [comment]
If ready please:
* Remove `WIP` from title.
* Merge and deploy

**Comment by IshaDakota** [comment]
merged & deployed

**Pull request merged**
